# ── Perfil PROD (Docker / producción) ──
spring.datasource.url=jdbc:mysql://mysql:3306/db_user?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
eureka.client.service-url.defaultZone=http://eureka:9761/eureka
logging.level.com.foodmarket.user=INFO
logging.level.org.springframework.web=WARN
logging.level.org.hibernate=WARN
